projectType : runtime
slackChannel : data-weave-bot
enableSlackSuccessNotifications : true
enableSlackFailedTestsNotifications : true
enableAllureTestReportStage : false
enableReleaseStage : false
mavenSettingsXmlId : "data-weave-maven-settings"
junitTestResults: "**/target/data-weave-test-reports/TEST-*.xml"