name: Create Next Release
on: 
  workflow_dispatch:

jobs:
  create_release_branch:
    name: "Create Release Branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Get version to release
        id: version
        run: |
          mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec
          echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | cut -d '-' -f1)
      - name: Create release branch
        run: |
          sed -i "s/<revision>.*<\/revision>/<revision>${{ steps.version.outputs.version }}<\/revision>/" pom.xml

          git config user.name github-actions
          git config user.email github-actions@github.com

          git checkout -b "release/${{ steps.version.outputs.version }}"
          git add pom.xml
          git commit -m "Pin release version"
          git push --set-upstream origin "release/${{ steps.version.outputs.version }}"
  update_patch:
    name: "Bump patch on master"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Get Version parts
        id: version
        run: |
          mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec
          echo ::set-output name=versionMajor::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | cut -d '-' -f1 | cut -d '.' -f1)
          echo ::set-output name=versionMinor::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | cut -d '-' -f1 | cut -d '.' -f2)
          echo ::set-output name=versionPatch::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | cut -d '-' -f1 | cut -d '.' -f3)
      - name: Get Next patch version
        id: nextVersion
        run: |
          echo ::set-output name=version::${{ steps.version.outputs.versionMajor }}.${{ steps.version.outputs.versionMinor }}.$((${{ steps.version.outputs.versionPatch }}+1))-SNAPSHOT
      - name: Create bump PR
        run: |
          sed -i "s/<revision>.*<\/revision>/<revision>${{ steps.nextVersion.outputs.version }}<\/revision>/" pom.xml

          git config user.name github-actions
          git config user.email github-actions@github.com

          git checkout -b "bump/${{ steps.nextVersion.outputs.version }}"
          git add pom.xml
          git commit -m "Bump Patch version"
          git push --set-upstream origin "bump/${{ steps.nextVersion.outputs.version }}"

          gh pr create -B master -f -H "bump/${{ steps.nextVersion.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

