name: Master branch workflow
on:
  push:
    branches:
      - master

jobs:
  compile_test:
    uses: ./.github/workflows/test.yml
  deploy_qax:
    needs: compile_test
    uses: ./.github/workflows/deploy.yml
    with:
      server-id: exchange-qax-coco
      mvn-profile: qax
      exchange-org-id: d4e2bceb-baae-484c-92f3-3cc272256c7f
      environment: qax
    secrets:
      EXCHANGE_USERNAME: ${{ secrets.EXCHANGE_USERNAME }}
      EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
      